version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "8081:80"
    depends_on:
      - app
  app:
    image: myapp:alpine
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"